### ISSUE TITLE
Error when reading in model checkpoint

### ISSUE THREAD

**Issue by NielsRogge** [lesterpjy/numeric-t5#2]
Hi,

I'd like to read in the model and convert it to PyTorch. 

I use the following code snippet to read in the weights:

```
from transformers import T5Tokenizer, TFT5ForConditionalGeneration

tokenizer = T5Tokenizer.from_pretrained('t5-small')
model = TFT5ForConditionalGeneration.from_pretrained('t5-small')
model.compile()
model.load_weights("/content/drive/MyDrive/NT5/Checkpoints/model_chkpt_e_42_vl_0.04173539.h5")
```

The checkpoint is stored in my local Drive.

However, this is giving me the following error:

```
All model checkpoint layers were used when initializing TFT5ForConditionalGeneration.

All the layers of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-afea930cf1a9> in <module>()
      4 model = TFT5ForConditionalGeneration.from_pretrained('t5-small')
      5 #model.compile()
----> 6 model.load_weights("/content/drive/MyDrive/NT5/Checkpoints/model_chkpt_e_42_vl_0.04173539.h5")

1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py in load_weights(self, filepath, by_name, skip_mismatch, options)
   2232             f, self.layers, skip_mismatch=skip_mismatch)
   2233       else:
-> 2234         hdf5_format.load_weights_from_hdf5_group(f, self.layers)
   2235 
   2236   def _updated_config(self):

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in load_weights_from_hdf5_group(f, layers)
    686                      'containing ' + str(len(layer_names)) +
    687                      ' layers into a model with ' + str(len(filtered_layers)) +
--> 688                      ' layers.')
    689 
    690   # We batch weight value assignments in a single backend call

ValueError: You are trying to load a weight file containing 4 layers into a model with 3 layers.
```

How to resolve this?

Notebook to reproduce: https://colab.research.google.com/drive/1vVORlnUAv1Tre71gEoh14C1fZvig0Vd1?usp=sharing

**Comment by yintrigue** [comment]
Hello Niels, thanks for reaching out. A couple of points:

- The issue you have is because our model subclasses TFT5ForConditionalGeneration: DROPBaseT5(transformers.TFT5ForConditionalGeneration). So if you use the codes from the Prediction Playground section (the last section of our notebook), it should work.

      model_play = DROPBaseT5.from_pretrained(PLAY_MODEL)  
      model_play.compile()    
      model_play.load_weights(PLAY_MODEL_PATH)

- We trained all our models on TPU using Colab. In theory, the codes should work for both TPU and GPU, but we have never fully tested it on GPU.
- We are now attempting to perform more experiments. Unfortunately, the new updates from Tensorflow and HuggingFace are causing some very odd bugs that prevent us from training on TPU. We will either spend time fixing the bugs for the latest verion of Tensorflow, or maybe port the whole thing over to PyTorch. Please keep us updated on your progress using PyTorch.

**Comment by yintrigue** [comment]
FYI: We just updated the repo. We are now including both our best and second-best models. The model you have from the previous version of repo is our second-best performing model. We have also included the evaluation reports for the two models as a reference.

**Comment by NielsRogge** [comment]
Hi,

Thanks for the quick reply. Unfortunately, this also gives me the same error:

```
model_play = DROPBaseT5.from_pretrained(PLAY_MODEL)  
model_play.compile()    
model_play.load_weights(PLAY_MODEL_PATH)
```
It says `ValueError: You are trying to load a weight file containing 4 layers into a model with 3 layers`. I know why it occurs: when printing `model_play.summary()`, I get this:

```
Model: "drop_base_t5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
shared (TFSharedEmbeddings)  multiple                  16449536  
_________________________________________________________________
encoder (TFT5MainLayer)      multiple                  18881280  
_________________________________________________________________
decoder (TFT5MainLayer)      multiple                  25175808  
=================================================================
Total params: 60,506,626
Trainable params: 60,506,624
Non-trainable params: 2
_________________________________________________________________
```
In other words, we have 3 layers, "shared", an "encoder" and "decoder". However, the .h5 file has an additional loss layer, as seen by running the following:

```
import json
import h5py

filename = '/content/drive/MyDrive/NT5/Checkpoints/model_chkpt_e_42_vl_0.04173539.h5'

with h5py.File(filename, "r") as f:
    # List all groups
    print("Keys: %s" % f.keys())
```

which prints:
`Keys: <KeysViewHDF5 ['decoder', 'encoder', 'loss', 'shared']>
`
Notebook to reproduce: https://colab.research.google.com/drive/1vVORlnUAv1Tre71gEoh14C1fZvig0Vd1?usp=sharing

Normally, it should just randomly initialize the loss layer (as is done in your notebook, because it prints): 
```
All model checkpoint weights were used when initializing DROPBaseT5.

Some weights of DROPBaseT5 were not initialized from the model checkpoint at t5-small and are newly initialized: ['loss']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```
I think this is a bug on Tensorflow's side (see https://github.com/keras-team/keras/issues/10417#issuecomment-435620108). To resolve it, I should probably either add the loss to the model, or remove the loss from the checkpoint.

If I get a PyTorch version working, I'll let you know. To me, PyTorch is a breeze to use compared to Tensorflow.

**Comment by NielsRogge** [comment]
If you can provide an easy way to read in all weights as Numpy arrays, then I convert it to PyTorch.

```
model_play = DROPBaseT5.from_pretrained("t5-small")  
model_play.compile() 
model_play.load_weights("/content/drive/MyDrive/NT5/Checkpoints/model_chkpt_e_42_vl_0.04173539.h5", by_name=True, skip_mismatch=True)
```
prints:
```
All model checkpoint layers were used when initializing DROPBaseT5.

Some layers of DROPBaseT5 were not initialized from the model checkpoint at t5-small and are newly initialized: ['loss']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
WARNING:tensorflow:Skipping loading of weights for layer encoder due to mismatch in shape ((32, 8) vs (512, 512)).
WARNING:tensorflow:Skipping loading of weights for layer encoder due to mismatch in shape ((512, 512) vs (32, 8)).
WARNING:tensorflow:Skipping loading of weights for layer decoder due to mismatch in number of weights (80 vs 81).
```

**Comment by yintrigue** [comment]
Ouch. I researched online a bit. It looks like many people are having similar issues. The real problem for our case here is that the new version of Tensorflow is not backwards compatible. The update on Keras seems to be causing this error.

Here's a simplified notebook with a prediction background that works: https://drive.google.com/file/d/18r92ZpQA6NqNDjqhY5TrhFSRmNl5q2Ln/view?usp=sharing

A revert of Tensorflow version should be sufficient, but here's a list of the package versions we used previously. 

    !pip install 'tensorflow==2.3.0'
    !pip install 'transformers==3.5.1'
    !pip install 'datasets==1.1.2'
    !pip install 'allennlp-models==1.2.1'

**Comment by NielsRogge** [comment]
Ok great, I am now able to have 2 notebooks to compare the outputs of the TF and PyTorch models on the same input data. 

TF notebook: https://drive.google.com/file/d/1VuXCrIErTr1RbnO3o1gQqRimkZgE5_xT/view?usp=sharing
PyTorch notebook: https://colab.research.google.com/drive/1vVORlnUAv1Tre71gEoh14C1fZvig0Vd1?usp=sharing

However, testing on the same input data (namely the following):
```
context = "On 12 January, the Tsar appointed Dmitri Feodorovich Trepov as governor in St Petersburg and dismissed the Minister of the Interior, Pyotr Sviatopolk-Mirskii, on 18 February\u00a0\u00a01905. He appointed a government commission \"to enquire without delay into the causes of discontent among the workers in the city of St Petersburg and its suburbs\" in view of the strike movement. The commission was headed by Senator NV\u00a0Shidlovsky, a member of the State Council, and included officials, chiefs of government factories, and private factory owners. It was also meant to have included workers' delegates elected according to a two-stage system. Elections of the workers delegates were, however, blocked by the socialists who wanted to divert the workers from the elections to the armed struggle. On 5 March\u00a0\u00a01905, the Commission was dissolved without having started work. Following the assassination of his uncle, the Grand Duke Sergei Aleksandrovich, on 17 February\u00a0\u00a01905, the Tsar made new concessions. On 18 February\u00a0\u00a01905 he published the Bulygin Rescript, which promised the formation of a consultative assembly, religious tolerance, freedom of speech  and a reduction in the peasants' redemption payments. On 24 and 25 May\u00a0\u00a01905, about 300 Zemstvo and municipal representatives held three meetings in Moscow, which passed a resolution, asking for popular representation at the national level. On 6 June\u00a0\u00a01905, Nicholas II had received a Zemstvo deputation. Responding to speeches by Prince Sergei Trubetskoi and Mr Fyodrov, the Tsar confirmed his promise to convene an assembly of people's representatives."
question = "The Tsar appointed Dmitri Feodorovich Trepov as governor in St. Petersburg on what date?"
```

The TF model (DropBaseT5) answers this question correctly (`T5 Answer:  12 January1905`) whereas the PyTorch model does not (`T5 Answer:  <pad>2 January</s>`). So now I'm doing some model surgery to figure out where the two models diverge. When performing a forward pass with `output_hidden_states=True`, I see that the intermediate hidden states of both models diverge after the first encoder block. They are still the same for the first block (when printing `outputs.encoder_hidden_states[0]`):

TF:
```
<tf.Tensor: shape=(1, 512, 512), dtype=float32, numpy=
array([[[  7.897771  ,  -8.246029  ,  13.170712  , ..., -12.20601   ,
           0.8796458 ,  -1.4387037 ],
        [-39.4935    ,   5.6590085 ,  36.542862  , ..., -31.460115  ,
          24.468758  ,   4.786658  ],
        [  7.835873  ,   5.0557923 ,  16.073236  , ...,   4.7340393 ,
          27.668737  ,   3.6328409 ],
        ...,
        [ -2.0149221 ,   0.19650759,  -6.98998   , ...,  -0.27544716,
           2.7134862 ,  -2.7739093 ],
        [ -2.0149221 ,   0.19650759,  -6.98998   , ...,  -0.27544716,
           2.7134862 ,  -2.7739093 ],
        [ -2.0149221 ,   0.19650759,  -6.98998   , ...,  -0.27544716,
           2.7134862 ,  -2.7739093 ]]], dtype=float32)>
```
PyTorch:
```
tensor([[[  7.8978,  -8.2460,  13.1707,  ..., -12.2060,   0.8796,  -1.4387],
         [-39.4935,   5.6590,  36.5429,  ..., -31.4601,  24.4688,   4.7867],
         [  7.8359,   5.0558,  16.0732,  ...,   4.7340,  27.6687,   3.6328],
         ...,
         [ -2.0149,   0.1965,  -6.9900,  ...,  -0.2754,   2.7135,  -2.7739],
         [ -2.0149,   0.1965,  -6.9900,  ...,  -0.2754,   2.7135,  -2.7739],
         [ -2.0149,   0.1965,  -6.9900,  ...,  -0.2754,   2.7135,  -2.7739]]],
       grad_fn=<EmbeddingBackward>)
```

but when printing `outputs.encoder_hidden_states[1]`, they are different:
TF:
```
<tf.Tensor: shape=(1, 512, 512), dtype=float32, numpy=
array([[[ 20.25953   ,  -5.662456  ,  55.343777  , ..., -11.487041  ,
          19.10796   ,  -7.6530476 ],
        [-63.758785  ,  20.052355  , 105.397644  , ..., -28.91057   ,
          68.52983   ,   4.3783875 ],
        [-18.511189  ,  25.616327  ,  99.94359   , ...,  -5.2988353 ,
          79.849     ,   0.15241623],
        ...,
        [ 11.568646  ,  15.806059  ,   9.762495  , ..., -25.421597  ,
          34.28335   ,  36.374367  ],
        [ 11.560502  ,  15.713228  ,   9.816258  , ..., -25.415972  ,
          34.259575  ,  36.480408  ],
        [ 12.028919  ,  15.895866  ,   9.702923  , ..., -25.625862  ,
          34.17133   ,  36.574318  ]]], dtype=float32)>
```
PyTorch:
```
tensor([[[ 1.9698e+01, -6.6009e+00,  5.4872e+01,  ..., -1.1798e+01,
           1.8099e+01, -7.6112e+00],
         [-6.3903e+01,  1.9910e+01,  1.0524e+02,  ..., -2.9076e+01,
           6.8337e+01,  4.3270e+00],
         [-1.8689e+01,  2.5486e+01,  9.9887e+01,  ..., -5.3764e+00,
           7.9858e+01,  5.1796e-02],
         ...,
         [ 1.0856e+01,  1.4331e+01,  1.0370e+01,  ..., -2.6385e+01,
           3.3502e+01,  3.7757e+01],
         [ 1.0856e+01,  1.4331e+01,  1.0370e+01,  ..., -2.6385e+01,
           3.3502e+01,  3.7757e+01],
         [ 1.0856e+01,  1.4331e+01,  1.0370e+01,  ..., -2.6385e+01,
           3.3502e+01,  3.7757e+01]]], grad_fn=<AddBackward0>)
```

**Comment by yintrigue** [comment]
I am surprised that PyTorch would output different answers. Models weights are exactly the same so the answer should be the same. I need to read through your PyTorch notebook in details, but did you add special tokens to SentencePiece, and set up the right max lengths for encoder/decoder?

    ENCODER_MAX_LEN = 512 # must be consistent with configs used to build TFRecords
    DECODER_MAX_LEN = 54 # must be consistent with configs used to build TFRecords
    TOKENIZER = transformers.AutoTokenizer.from_pretrained(T5_MODEL)
    special_tokens_dict = {'additional_special_tokens': ['0','1','2','3', '4', '5', '6', '7', '8', '9', '<ss>', '<sv>']}
    num_added_toks = TOKENIZER.add_special_tokens(special_tokens_dict)

And yes, we do plan to train a bigger model (T5-base), and I think your notebook will be a big help.

**Comment by NielsRogge** [comment]
Damn, I forgot to add this:

```
special_tokens_dict = {'additional_special_tokens': ['0','1','2','3', '4', '5', '6', '7', '8', '9', '<ss>', '<sv>']}
num_added_toks = TOKENIZER.add_special_tokens(special_tokens_dict)
```
Turns out the bug with the relative position bias is only marginal. So now my PyTorch model entirely works!

**Comment by NielsRogge** [comment]
I've uploaded a checkpoint (the best performing one) to the hub of HuggingFace: https://huggingface.co/nielsr/nt5-small-rc1

The weights are stored in the cloud, so you can access them from anywhere.

**Comment by yintrigue** [comment]
This is great. Thank you so much!

**Comment by NielsRogge** [comment]
You're welcome!

I tested it with the following context + question: 

```
context: "There are six frogs on a log. Two leave, but three join".
question: "The number of forgs on the log is now?"
```

It answers six. Any idea why this is the case? Is this example too short for the model?

**Comment by lesterpjy** [comment]
In this case the model might simply be extracting the "six" from the context, instead of recognizing that a calculation is necessary to get to the answer. You can try expanding the second sentence with more context, something like "Two frogs left the log, but then three frogs joined." This might help the model recognize that the "two" and "three" in the second sentence refer to the frogs on the log. However, the model might still make these mistakes.

The benefit of our method is that the model scale is significantly smaller, and it does not use a separate symbol module (just out-of-box T5), but as you can see on the DROP leaderboard, its performance is nearly 20 F1 score away from SOTA. We would like to demonstrate a more direct comparison with SOTA at some point, likely through training a model of similar scale, but at the moment NT5 with T5-small makes these mistakes.

**Comment by NielsRogge** [comment]
Ok, yes I made the context more longer as you said, but then it's doesn't predict anything. 

And yes I like the simplicity of NT5. It basically shows that language models can learn anything, given the right data, right?
